apiVersion: v1
kind: Service
metadata:
  name: vehicle-rental-backend
  namespace: vehicle-rental
spec:
  selector:
    app: vehicle-rental-backend
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
