apiVersion: v1
kind: Service
metadata:
  name: vehicle-service
  namespace: vehicle-system
  labels:
    app: vehicle-service
spec:
  selector:
    app: vehicle-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
